# Generated by Django 2.2.7 on 2020-04-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_addexpenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexpenses',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
