# Generated by Django 2.2.7 on 2020-04-30 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20200428_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensePaidAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=50)),
                ('food_expense', models.FloatField()),
                ('pub_bill', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.AddRoommate')),
            ],
        ),
    ]
