# Generated by Django 2.2.7 on 2020-04-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_expensepaidamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensepaidamount',
            name='pub_bill',
        ),
    ]
