# Generated by Django 2.2.7 on 2020-04-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_remove_expensepaidamount_pub_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensepaidamount',
            name='no_of_days',
            field=models.IntegerField(null=True),
        ),
    ]
