# Generated by Django 2.2.7 on 2020-04-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_expensepaidamount_no_of_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='PUBBillAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_units', models.FloatField()),
                ('refuse_amt', models.FloatField()),
                ('water_amt', models.FloatField()),
                ('gst', models.FloatField()),
            ],
        ),
    ]
