# Generated by Django 2.2.7 on 2020-05-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_pubbillamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubbillamount',
            name='total_amt',
            field=models.FloatField(null=True),
        ),
    ]
