# Generated by Django 2.2.7 on 2020-05-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_expensepaidamount_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubbillamount',
            name='food_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
