# Generated by Django 2.2.7 on 2020-05-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_pubbillamount_food_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensepaidamount',
            name='total_paid_pub',
            field=models.FloatField(null=True),
        ),
    ]
